In [11]:
import tensorflow as tf

In [6]:
# a = tf.ones([1,3])
# b = tf.fill([1,3], 3.)
# print(a)
# print(b)
# print(b.numpy())

In [9]:
a = tf.fill([1, 2], 3.)
print(tf.pow(a, 3))

tf.Tensor([[27. 27.]], shape=(1, 2), dtype=float32)


In [13]:
features = tf.constant([12 ,23 ,10, 17])
labels = tf.constant([0, 1, 1, 0])
dataset = tf.data.Dataset.from_tensor_slices((features, labels))
for element in dataset:
    print(element)


(<tf.Tensor: shape=(), dtype=int32, numpy=12>, <tf.Tensor: shape=(), dtype=int32, numpy=0>)
(<tf.Tensor: shape=(), dtype=int32, numpy=23>, <tf.Tensor: shape=(), dtype=int32, numpy=1>)
(<tf.Tensor: shape=(), dtype=int32, numpy=10>, <tf.Tensor: shape=(), dtype=int32, numpy=1>)
(<tf.Tensor: shape=(), dtype=int32, numpy=17>, <tf.Tensor: shape=(), dtype=int32, numpy=0>)


In [18]:

import numpy as np
y = tf.constant([1.01, 2.01, -0.66])
y_pro = tf.nn.softmax(y)
print('After softmax, y_pro is: ', y_pro)
# np.argmax是返回输入的最大值的下标
print(np.argmax(y_pro))
print(np.argmin(y_pro))

After softmax, y_pro is:  tf.Tensor([0.25598174 0.69583046 0.0481878 ], shape=(3,), dtype=float32)
1
2


In [14]:
classes = 3
labels = tf.constant([1, 0, 2])
output = tf.one_hot(labels, depth=classes)
print(output)


tf.Tensor(
[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [21]:
# assign_sub 用于参数自更新
w = tf.Variable(4)
w.assign_sub(1)
print(w)
print(w.numpy())


<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=3>
3


In [24]:
test = np.array([[1, 2, 3],
               [2, 3, 4],
               [5, 4 , 3],
               [8, 7, 2]])

print(test.shape)
print(test)



(4, 3)
[[1 2 3]
 [2 3 4]
 [5 4 3]
 [8 7 2]]


In [27]:
print(np.argmax(test, axis=0))
print(np.argmax(test, axis=1))

[3 3 1]
[2 2 0 0]


In [29]:
from sklearn.datasets import load_iris

data = load_iris()
x_data = data.data
y_data = data.target
print(x_data.shape)


(150, 4)


In [31]:
import pandas as  pd

x_data = pd.DataFrame(x_data, columns=['花萼长度', '花萼宽度', '花瓣长度', '花瓣宽度'])
# 设置列名对齐
pd.set_option('display.unicode.east_asian_width', True)
x_data['类别'] = y_data
print("x_data add a column: \n", x_data)

x_data add a column: 
      花萼长度  花萼宽度  花瓣长度  花瓣宽度  类别
0         5.1       3.5       1.4       0.2     0
1         4.9       3.0       1.4       0.2     0
2         4.7       3.2       1.3       0.2     0
3         4.6       3.1       1.5       0.2     0
4         5.0       3.6       1.4       0.2     0
..        ...       ...       ...       ...   ...
145       6.7       3.0       5.2       2.3     2
146       6.3       2.5       5.0       1.9     2
147       6.5       3.0       5.2       2.0     2
148       6.2       3.4       5.4       2.3     2
149       5.9       3.0       5.1       1.8     2

[150 rows x 5 columns]


In [33]:

# tf.where
a = tf.constant([1, 2,3,1,1])
b = tf.constant([0, 1,3, 4,5])
c = tf.where(tf.greater(a, b), a, b)
print(c.numpy())

[1 2 3 4 5]


In [34]:

# rand
print(np.random.rand())

0.09639783626197707


In [36]:
print(np.random.rand(2,3))


[[0.88233832 0.13388076 0.81498543]
 [0.99402538 0.25304467 0.18997337]]


In [39]:

a = tf.constant([1,2,3])
b = tf.constant([4, 5,6])
print(np.hstack((a, b)))


[1 2 3 4 5 6]


In [ ]:

x, y  = np.mgrid